HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/Data/LootRuling.cs
HimbeertoniRaidTool/Data/Structs.cs
HimbeertoniRaidTool/HRTPlugin.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/locale/de.json

Add Localization support to the Addon including German translations

Localization

---

HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/Data/EtroConnector.cs
HimbeertoniRaidTool/Data/GearItem.cs
HimbeertoniRaidTool/HRTPlugin.cs
HimbeertoniRaidTool/Helper.cs
HimbeertoniRaidTool/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs

Support for Materia
- Automatically updates materia from ingame and etro
- Take Materia into account for Bis comparision
- Add button to update bis sets from etro
- More Ui improvements

12 track materia on items

---

HimbeertoniRaidTool/Data/CuratedData.cs
HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/Data/GearItem.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/HimbeertoniRaidTool.json
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs

* added correcct Ui for Endsinger Weapons & Aglaia Armor
* examining from HRT Ui is broken for the moment -> disabled

Update for 6.1

---

HimbeertoniRaidTool/Data/CuratedData.cs
HimbeertoniRaidTool/Data/Items.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/packages.lock.json
UnitTestsData/UnitTestsData.csproj

22 switch to net6

---

HimbeertoniRaidTool/Data/AllaganLibrary.cs
HimbeertoniRaidTool/Data/PlayableClass.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/HimbeertoniRaidTool.json
HimbeertoniRaidTool/LootMaster/LootMaster.cs
HimbeertoniRaidTool/packages.lock.json

Fixed crashing in Solo/detailed view on empty classes
* Make more new user ffriedly by filling Solo Page on first use

25 plugin crashing when attempting to add a player

---

HimbeertoniRaidTool/Configuration.cs
HimbeertoniRaidTool/HRTPlugin.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/HimbeertoniRaidTool.json
HimbeertoniRaidTool/LootMaster/LootSessionUI.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/HrtUI.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs
HimbeertoniRaidTool/UI/UiSortableList.cs
HimbeertoniRaidTool/UI/WelcomeWindow.cs

Add tooltips to all buttons and a welcome message window

UI improvements 1

---

HimbeertoniRaidTool/Configuration.cs
HimbeertoniRaidTool/Connectors/BaseConnector.cs
HimbeertoniRaidTool/Connectors/EtroConnector.cs
HimbeertoniRaidTool/Connectors/XIVAPIConnector.cs
HimbeertoniRaidTool/Data/AllaganLibrary.cs
HimbeertoniRaidTool/Data/Character.cs
HimbeertoniRaidTool/Data/CuratedData.cs
HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/Data/GearSet.cs
HimbeertoniRaidTool/Data/PlayableClass.cs
HimbeertoniRaidTool/Data/Player.cs
HimbeertoniRaidTool/DataManagement/DataManager.cs
HimbeertoniRaidTool/Helper.cs
HimbeertoniRaidTool/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/LootMaster/LootMaster.cs
HimbeertoniRaidTool/LootMaster/LootSessionUI.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs
UnitTestsData/EnumsWithFunctionality.cs

* Adapt handling of jobs to FFXIVClient
* Adapt handling of race/clan to Tribe (as FFXIVClient)
* Adapt stat calculation to use in-game information (where possible)
* Changes to make Examine more consistent/stable
* No more empty AST jobs (if something went wrong)

Incorporate structural changes/optimizations discoverd while incorporating lodestone data

---

HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs
HimbeertoniRaidTool/packages.lock.json

Using XivCommon for Examine functionality, since it is up to date and working now
Includes more detailed "errors" if the functionality is unavailable

Fixed update gear button (#27)

---

HimbeertoniRaidTool/LootMaster/LootMaster.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/DrawDataExtension.cs
HimbeertoniRaidTool/UI/EditWindows.cs

aditionally includes
* some tidying up of Ui
* better auto creation of groups (add support for solo and 4-player groups)

Revamp of edit player interface

---

HimbeertoniRaidTool/Data/AllaganLibrary.cs
HimbeertoniRaidTool/HRTPlugin.cs

Reworked internal structures. Helps performance and readability
Added partial support for level 80/70

Rework Allagan library

---

HimbeertoniRaidTool/Data/CuratedData.cs
HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/Data/GearSet.cs
HimbeertoniRaidTool/Data/Items.cs
HimbeertoniRaidTool/Data/PlayableClass.cs
HimbeertoniRaidTool/DataManagement/CharacterDB.cs
HimbeertoniRaidTool/LootMaster/LootSessionUI.cs
HimbeertoniRaidTool/LootMaster/LootmasterUI.cs

A lot of internal code work to facilitate the following
- eliminate reevaluation of values that do not change after load
- improve readability of code
- make code more robust
- performance improvements
- better separation of Ui and data to make future optimization and feature addition easier

Code Optimization

---

HimbeertoniRaidTool/Data/AllaganLibrary.cs

Some rework to make code more readable and give a better undestanding of inner workings
Aditionally added first draft of damage calculations

Rework and addition of damage in Allagan library

---

HimbeertoniRaidTool/Modules/LootMaster/LootMasterModule.cs
HimbeertoniRaidTool/Modules/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/Modules/WelcomeWindow/WelcomeWindow.cs
HimbeertoniRaidTool/UI/HrtUI.cs

You think we missing any important message types? Else merge

Implement message system

---

HimbeertoniRaidTool/Connectors/BaseConnector.cs
HimbeertoniRaidTool/Connectors/ConnectorPool.cs
HimbeertoniRaidTool/Connectors/EtroConnector.cs
HimbeertoniRaidTool/Connectors/XIVAPIConnector.cs
HimbeertoniRaidTool/Data/GearSet.cs
HimbeertoniRaidTool/DataManagement/DataManager.cs
HimbeertoniRaidTool/DataManagement/GearDB.cs
HimbeertoniRaidTool/HRTPlugin.cs
HimbeertoniRaidTool/Modules/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/Modules/LootMaster/LootMasterConfiguration.cs
HimbeertoniRaidTool/Modules/LootMaster/LootMasterModule.cs
HimbeertoniRaidTool/Modules/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs

- WebApi Connectors now have caching and rate limiting built in
- Gearsets fetched from etro now keep track of last fetsched alongside last changed
- gear sets that haven't been updated for a specified amount of time can be updated automatically (Opt-In)

Rework of WebApi connections (specifically etro.gg)

---

HimbeertoniRaidTool/Configuration.cs
HimbeertoniRaidTool/DataManagement/CharacterDB.cs
HimbeertoniRaidTool/DataManagement/DataManager.cs
HimbeertoniRaidTool/DataManagement/GearDB.cs
HimbeertoniRaidTool/Modules/LootMaster/LootMasterModule.cs
HimbeertoniRaidTool/UI/EditWindows.cs

- Periodically save data with adjustable interval (opt-out)
- Save after big operations and saving in edit windows

56 save data more often

---

HimbeertoniRaidTool/Data/Character.cs
HimbeertoniRaidTool/Data/Enums.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/HrtUI.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs

- You can edit tribe manually now
- Job to add is now searchable

54 add tribe to player edit

---

HimbeertoniRaidTool/Modules/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/HrtUI.cs

All windows and designs now scale according to ImGui's gloabl font scale

55 add support for dpi scaling

---

HimbeertoniRaidTool/Data/Character.cs
HimbeertoniRaidTool/Data/Items.cs
HimbeertoniRaidTool/Data/PlayableClass.cs
HimbeertoniRaidTool/Helper.cs
HimbeertoniRaidTool/Modules/LootMaster/GearRefresherOnExamine.cs
HimbeertoniRaidTool/Modules/LootMaster/LootMasterModule.cs
HimbeertoniRaidTool/Modules/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs

Optimization

---

HimbeertoniRaidTool/Data/CuratedData.cs
HimbeertoniRaidTool/Data/Items.cs
HimbeertoniRaidTool/Data/Loot.cs

switch from name based to id bnased lookup for gear source, this ends the necessity to cache this

Rework detection of gear source

---

HimbeertoniRaidTool/Configuration.cs
HimbeertoniRaidTool/Data/Items.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/Modules/LootMaster/LootMasterConfiguration.cs
HimbeertoniRaidTool/Modules/LootMaster/LootSessionUI.cs
HimbeertoniRaidTool/Modules/LootMaster/LootmasterUI.cs
HimbeertoniRaidTool/UI/ColorHelper.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs
HimbeertoniRaidTool/packages.lock.json

* adds more tooltips
* you can ignore materia for BiS comparison

UI: more customization

---

HimbeertoniRaidTool/HimbeertoniRaidTool.csproj
HimbeertoniRaidTool/HimbeertoniRaidTool.yaml
HimbeertoniRaidTool/Modules/LootMaster/LootSessionUI.cs

V1.1.1 hotfix

---

HimbeertoniRaidTool/Connectors/LodestoneConnector.cs
HimbeertoniRaidTool/HimbeertoniRaidTool.yaml

There is a language mismatch for item lookups

Fix: cannot look up characters from lodestone

---

HimbeertoniRaidTool/DataManagement/CharacterDB.cs
HimbeertoniRaidTool/Modules/Core/CoreConfig.cs
HimbeertoniRaidTool/Modules/Core/Ui/ChangeLogUi.cs
HimbeertoniRaidTool/Modules/LootMaster/LootMasterConfiguration.cs
HimbeertoniRaidTool/Modules/LootMaster/LootRuling.cs
HimbeertoniRaidTool/Modules/LootMaster/Ui/LootSessionUI.cs
HimbeertoniRaidTool/Modules/LootMaster/Ui/LootmasterUI.cs
HimbeertoniRaidTool/Modules/LootMaster/Ui/QuickCompare.cs
HimbeertoniRaidTool/Services/ConfigurationManager.cs
HimbeertoniRaidTool/UI/DrawDataExtension.cs
HimbeertoniRaidTool/UI/EditWindows.cs
HimbeertoniRaidTool/UI/HrtWindow.cs
HimbeertoniRaidTool/UI/ImGuiHelper.cs
HimbeertoniRaidTool/UI/Inventory.cs
HimbeertoniRaidTool/UI/ItemSelection.cs
HimbeertoniRaidTool/UI/UiHelpers.cs
HimbeertoniRaidTool/UI/UiSortableList.cs

I noticed with ImGui assertions enabled that there's some mismatched PushId/PopIds. I think I found the right one, but I converted everything to ImRaii to make it easier to manage it all (since ImRaii is already used in some places in this project).
I ended up doing a little bit of refactoring and extracting some methods in places to reduce the amount of nesting, but tried not to go too overboard to make it a bit less bad to review.
It might be easier to review this with "hide whitespace changes" turned on:

Use ImRaii everywhere
